version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: h*uYfBz00#vSry3b
      MYSQL_DATABASE: soilless-farm
      MYSQL_USER: soilless-farm
      MYSQL_PASSWORD: h*uYfBz00#vSry3b
    ports:
      - "3307:3306"
